### ISSUE TITLE
not found css/style.css

### ISSUE THREAD

**Issue by rainsuny** [keik/bookmanager-with-spring-boot#12]
not found css/style.css

**Comment by keik** [comment]
(This project is abandoned)

css files (css/style.css) will be built from *.less files and distributed into [src/main/resources/static](https://github.com/keik/bookmanager-with-spring-boot/tree/master/src/main/resources/static) by grunt. You must install Node.js and execute

```
% npm install grunt -g
% npm install
% grunt install
```
